### ISSUE TITLE
注文のキャンセルができない(RestoreAfterCancel.php)

### ISSUE THREAD

**Issue by fd-nishimura** [komoju/komoju-magento#20]
日本語で失礼します。

v1.2.0にアップデートしたところ、以下のエラーにより注文キャンセルができなくなりました。

```
[2024-08-01T00:36:16.166669+00:00] main.CRITICAL: Error: Call to a member function setIsActive() on null in {magento_root}/app/code/Komoju/Payments/Observer/RestoreAfterCancel.php:34
Stack trace:
#0 {magento_root}/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Komoju\Payments\Observer\RestoreAfterCancel->execute()
#1 {magento_root}/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#2 {magento_root}/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#3 {magento_root}/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#4 {magento_root}/vendor/magento/module-sales/Model/Order.php(1281): Magento\Framework\Event\Manager\Proxy->dispatch()
#5 {magento_root}/vendor/magento/module-sales/Model/Service/OrderService.php(107): Magento\Sales\Model\Order->cancel()
#6 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->cancel()
#7 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent()
#8 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}()
#9 {magento_root}/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(23): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins()
#10 {magento_root}/vendor/magento/module-sales/Controller/Adminhtml/Order/Cancel.php(35): Magento\Sales\Model\Service\OrderService\Interceptor->cancel()
#11 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Cancel->execute()
#12 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callParent()
#13 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#14 {magento_root}/generated/code/Magento/Sales/Controller/Adminhtml/Order/Cancel/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callPlugins()
#15 {magento_root}/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->execute()
#16 {magento_root}/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#17 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#18 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callParent()
#19 {magento_root}/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#20 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#21 {magento_root}/app/code/Magetop/Marketplace/Plugin/App/Action/Context.php(54): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#22 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(135): Magetop\Marketplace\Plugin\App\Action\Context->aroundDispatch()
#23 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->Magento\Framework\Interception\{closure}()
#24 {magento_root}/generated/code/Magento/Sales/Controller/Adminhtml/Order/Cancel/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->___callPlugins()
#25 {magento_root}/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Cancel\Interceptor->dispatch()
#26 {magento_root}/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#27 {magento_root}/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#28 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#29 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#30 {magento_root}/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#31 {magento_root}/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#32 {magento_root}/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#33 {magento_root}/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#34 {magento_root}/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#35 {main} {"exception":"[object] (Error(code: 0): Call to a member function setIsActive() on null at {magento_root}/app/code/Komoju/Payments/Observer/RestoreAfterCancel.php:34)"} []
``` 

プラグインの競合が原因の可能性がありますが、以前はキャンセル処理できていたと思うので、解決の手伝い頂けないでしょうか？
ご検討のほどよろしくお願い致します。

**Comment by Dinwy** [comment]
Thank you for your report and sorry for the late response.
This problem is fixed in #22 and we will make a new release soon.

ご報告いただきありがとうございます。また、返信が遅くなり申し訳ありません。
この問題は #22 で修正されており、近日中に新しいリリースを行う予定です。
